name = "nix-config"

packages = [
  "cargo",
  "doppler",
  "gcc",
  "home-manager",
  "jq",
  "niv",
  "pre-commit",
  "shellcheck",
]

[env]
PRE_COMMIT_COLOR = "never"
SHELLCHECK_OPTS = "-e SC1008"
