name = "nix-config"

packages = [
  "cargo",
  "doppler",
  "gcc",
  "home-manager",
  "jq",
  "niv",
  "pre-commit",
  "shellcheck",
  "wget",
]

[[env]]
name = "PRE_COMMIT_COLOR"
value = "never"

[[env]]
name = "SHELLCHECK_OPTS"
value = "-e SC1008"
