#! /usr/bin/env nix-shell
#! nix-shell -i bash -p bash

# This script will update all of the sources.json files generated by niv

find . -type f -name "update-sources.sh" | while read -r updatescript; do
  pushd "$(dirname -- "$updatescript")" || exit
  ./update-sources.sh
  popd || exit
done

