# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4c3f908e-d79e-4f85-9ae2-bbd9b436762a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/1d515ecb-961b-40a0-804c-f0f8e03784b5";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/891A-1829";
      fsType = "vfat";
    };

  fileSystems."/mnt/BigHD" =
    { device = "/dev/disk/by-uuid/8ad11507-8742-468b-8c38-fb9a130a467c";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/128c2cbb-2d8d-45d1-8645-21dfaa10a09d"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
