# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@types/node-22.15.18" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "22.15.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-22.15.18.tgz";
        sha512 = "v1DKRfUdyW+jJhZNEI1PYy29S2YRxMV5AOO/x/SjKmW0acCIOqmbj6Haf9eHAhsPmrhlHSxEhv/1WszcLWV4cg==";
      };
    };
    "bun-types-1.2.13" = {
      name = "bun-types";
      packageName = "bun-types";
      version = "1.2.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/bun-types/-/bun-types-1.2.13.tgz";
        sha512 = "rRjA1T6n7wto4gxhAO/ErZEtOXyEZEmnIHQfl0Dt1QQSB4QV0iP6BZ9/YB5fZaHFQ2dwHFrmPaRQ9GGMX01k9Q==";
      };
    };
    "typescript-5.8.3" = {
      name = "typescript";
      packageName = "typescript";
      version = "5.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-5.8.3.tgz";
        sha512 = "p1diW6TqL9L07nNxvRMM7hMMw4c5XOo/1ibL4aAIGmSAt9slTE1Xgw5KWuof2uTOvCg9BY7ZRi+GaF+7sfgPeQ==";
      };
    };
    "undici-types-6.21.0" = {
      name = "undici-types";
      packageName = "undici-types";
      version = "6.21.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/undici-types/-/undici-types-6.21.0.tgz";
        sha512 = "iwDZqg0QAGrg9Rav5H4n0M64c3mkR59cJ6wQp+7C4nI0gsmExaedaYLNO44eT4AtBBwjbTiGPMlt2Md0T9H9JQ==";
      };
    };
  };
in
{
  "@types/bun" = nodeEnv.buildNodePackage {
    name = "_at_types_slash_bun";
    packageName = "@types/bun";
    version = "1.2.13";
    src = fetchurl {
      url = "https://registry.npmjs.org/@types/bun/-/bun-1.2.13.tgz";
      sha512 = "u6vXep/i9VBxoJl3GjZsl/BFIsvML8DfVDO0RYLEwtSZSp981kEO1V5NwRcO1CPJ7AmvpbnDCiMKo3JvbDEjAg==";
    };
    dependencies = [
      sources."@types/node-22.15.18"
      sources."bun-types-1.2.13"
      sources."undici-types-6.21.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "TypeScript definitions for bun";
      homepage = "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/bun";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@types/node" = nodeEnv.buildNodePackage {
    name = "_at_types_slash_node";
    packageName = "@types/node";
    version = "22.15.18";
    src = fetchurl {
      url = "https://registry.npmjs.org/@types/node/-/node-22.15.18.tgz";
      sha512 = "v1DKRfUdyW+jJhZNEI1PYy29S2YRxMV5AOO/x/SjKmW0acCIOqmbj6Haf9eHAhsPmrhlHSxEhv/1WszcLWV4cg==";
    };
    dependencies = [
      sources."undici-types-6.21.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "TypeScript definitions for node";
      homepage = "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  bun-types = nodeEnv.buildNodePackage {
    name = "bun-types";
    packageName = "bun-types";
    version = "1.2.13";
    src = fetchurl {
      url = "https://registry.npmjs.org/bun-types/-/bun-types-1.2.13.tgz";
      sha512 = "rRjA1T6n7wto4gxhAO/ErZEtOXyEZEmnIHQfl0Dt1QQSB4QV0iP6BZ9/YB5fZaHFQ2dwHFrmPaRQ9GGMX01k9Q==";
    };
    dependencies = [
      sources."@types/node-22.15.18"
      sources."undici-types-6.21.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Type definitions and documentation for Bun, an incredibly fast JavaScript runtime";
      homepage = "https://bun.sh";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  coc-tsserver = nodeEnv.buildNodePackage {
    name = "coc-tsserver";
    packageName = "coc-tsserver";
    version = "2.2.5";
    src = fetchurl {
      url = "https://registry.npmjs.org/coc-tsserver/-/coc-tsserver-2.2.5.tgz";
      sha512 = "nXEsUUKPKyms1XwxIih/9qWD0a5pFKarGjjoNwD1gCYPnojKIcpr8bDLWH4MFeV8aGs04rDj8Yv1uf5ZhNwihw==";
    };
    dependencies = [
      sources."typescript-5.8.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "javascript and typescript language features extension of coc.nvim";
      homepage = "https://github.com/neoclide/coc-tsserver#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  typescript = nodeEnv.buildNodePackage {
    name = "typescript";
    packageName = "typescript";
    version = "5.8.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/typescript/-/typescript-5.8.3.tgz";
      sha512 = "p1diW6TqL9L07nNxvRMM7hMMw4c5XOo/1ibL4aAIGmSAt9slTE1Xgw5KWuof2uTOvCg9BY7ZRi+GaF+7sfgPeQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "TypeScript is a language for application scale JavaScript development";
      homepage = "https://www.typescriptlang.org/";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  undici-types = nodeEnv.buildNodePackage {
    name = "undici-types";
    packageName = "undici-types";
    version = "7.9.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/undici-types/-/undici-types-7.9.0.tgz";
      sha512 = "TotbsoWjj1gHRlCBRKtFCKTg3HeHE87dLe3DkuWzQKlyQ0LQXP4pLTb3fBUhdcODdOoT8BkB4zdOShW57NH1rw==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "A stand-alone types package for Undici";
      homepage = "https://undici.nodejs.org";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
