{ pkgs, lib, config, osConfig, ... }:
let
  inherit (osConfig.custom.display) dp;
  inherit (config.lib.stylix) colors;
  inherit (config.stylix) polarity;
  # index 0 is bg in dark mode but tab/toolbar text in light mode; ayu-light's
  # base07 isn't dark enough to stay legible there, so light mode pins a
  # fixed dark value instead of the scheme color.
  darkAnchor = if polarity == "dark" then colors.withHashtag.base00 else "#000000";
  lightAnchor = colors.withHashtag.${if polarity == "dark" then "base07" else "base00"};
  # icons and the selection highlight share this slot; base0B/base0D read too
  # loud and grey lost too much color, so base0C (teal) is used instead.
  mutedAccent = colors.withHashtag.${if polarity == "dark" then "base04" else "base05"};
in
{

  stylix.targets.firefox = {
    enable = true;
    profileNames = [ "default" ];
  };

  home = {
    sessionVariables = {
      MOZ_USE_XINPUT2 = "1";
    };

    file.".mozilla/native-messaging-hosts/pywalfox.json".text = builtins.toJSON {
      name = "pywalfox";
      description = "Automatically theme your browser using the colors generated by Pywal";
      path = "${pkgs.writeShellScriptBin "pywalfox-native-host" ''
        exec ${pkgs.pywalfox-native}/bin/pywalfox start
      ''}/bin/pywalfox-native-host";
      type = "stdio";
      allowed_extensions = [ "pywalfox@frewacom.org" ];
    };

    # pywalfox reads these 16 slots positionally, so keys are zero-padded to
    # keep toJSON's alphabetic ordering numeric (unpadded, "color10" would
    # sort before "color2" and scramble the mapping).
    file.".cache/wal/colors.json" = {
      force = true;
      text = builtins.toJSON {
        wallpaper = "none";
        colors = {
          color00 = darkAnchor; # dark: background / light: active-tab text
          color01 = colors.withHashtag.base08;
          color02 = colors.withHashtag.base0B;
          color03 = mutedAccent; # light: icons / hover-highlight
          color04 = colors.withHashtag.base0D;
          color05 = colors.withHashtag.base0A; # light: icons_attention
          color06 = colors.withHashtag.base0C;
          color07 = colors.withHashtag.base05;
          color08 = colors.withHashtag.base03;
          color09 = colors.withHashtag.base08;
          color10 = mutedAccent; # dark: icons / hover-highlight
          color11 = colors.withHashtag.base0A;
          color12 = colors.withHashtag.base0D;
          color13 = colors.withHashtag.base0A; # dark: icons_attention
          color14 = colors.withHashtag.base0C;
          color15 = lightAnchor; # dark: active-tab text
        };
      };
    };

    # Only refresh if the native host is already running; otherwise pywalfox
    # picks up colors.json on next connect. pywalfox also persists its own
    # light/dark mode separately from stylix polarity, so it must be set
    # explicitly here or the role mapping (which array slot means what)
    # goes stale across specialisation switches.
    activation.reloadPywalfox = config.lib.dag.entryAfter [ "writeBoundary" ] ''
      if [ -S "''${TMPDIR:-/tmp}/pywalfox_socket_$(id -u)" ]; then
        run ${pkgs.pywalfox-native}/bin/pywalfox ${if polarity == "dark" then "dark" else "light"}
        run ${pkgs.pywalfox-native}/bin/pywalfox update
      fi
    '';
  };

  programs.firefox = {
    enable = true;
    configPath = ".mozilla/firefox";
    package = pkgs.wrapFirefox pkgs.firefox-esr-unwrapped {
      extraPolicies = {
        CaptivePortal = false;
        DisableFirefoxStudies = true;
        DisablePocket = true;
        DisableTelemetry = true;
        FirefoxHome = {
          Pocket = false;
          Snippets = false;
        };
        UserMessaging = {
          ExtensionRecommendations = false;
          SkipOnboarding = true;
        };
      };
    };

    profiles."default" = {
      name = "default";
      extensions = {
        force = true;
        packages = [ pkgs.nur.repos.rycee.firefox-addons.pywalfox ];
      };
      userChrome = ''
        .tab-text { font-size: ${toString (dp 14)}px !important; }
        :root { --focus-outline-color: transparent !important; }
      '';
      settings = {
        "font.size.variable.x-western" = lib.mkForce (dp 16);
        "browser.contentblocking.report.lockwise.enabled" = false;
        "browser.contentblocking.report.monitor.enabled" = false;
        "browser.tabs.groups.enabled" = false;
        "browser.display.use_system_colors" = false;
        "browser.download.useDownloadDir" = false;
        "devtools.theme" = "auto";
        "general.autoScroll" = true;
        "gfx.webrender.all" = true;
        "media.videocontrols.picture-in-picture.video-toggle.enabled" = false;
        "media.cubeb_latency_playback_ms" = 10;
        "widget.content.allow-gtk-dark-theme" = false;
        "browser.proton.contextmenus.enabled" = false;
        "browser.proton.doorhangers.enabled" = false;
        "browser.proton.enabled" = false;
        "browser.proton.modals.enabled" = false;
        "browser.proton.places-tooltip.enabled" = false;
        "browser.sessionstore.restore_tabs_lazily" = false;
        "browser.sessionstore.restore_on_demand" = false;
        "javascript.options.wasm_js_promise_integration" = true;
        "toolkit.legacyUserProfileCustomizations.stylesheets" = true;
      };
    };
  };

  custom.persistence.directories = [
    ".cache/mozilla"
    ".mozilla/firefox"
    ".config/pywalfox"
  ];
}
