name: "PR tests"
on:
  pull_request:
    branches: [master]

jobs:
  system:
    name: Build system
    strategy:
      matrix:
        machines:
          - nixos-desktop
          - nixos-t400
          - nixos-t520

    runs-on: ubuntu-latest
    steps:
    - name: Install nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Checkout repository
      uses: actions/checkout@v2.3.4

    - name: Build system
      run: nix run nixpkgs.nix-build-uncached -c nix-build-uncached -I nixos-hardware="$(jq -r '.["nixos-hardware"].url' ./nix/sources.json)" -I nur="$(jq -r '.["NUR"].url' ./nix/sources.json)" ci.nix -A $machine
      env:
        machine: ${{ matrix.machines }}

  home-manager:
    name: Build home-manager
    strategy:
      matrix:
        cachixName:
          - reedrw
    runs-on: ubuntu-latest
    steps:
    - name: Install nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Checkout repository
      uses: actions/checkout@v2.3.4

    - name: Build home-manager
      run: nix run nixpkgs.nix-build-uncached -c nix-build-uncached ci.nix -A home-manager

  shell:
    name: Build nix-shell
    strategy:
      matrix:
        cachixName:
          - reedrw

    runs-on: ubuntu-latest
    steps:
    - name: Install nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Checkout repository
      uses: actions/checkout@v2.3.4

    - name: Build nix-shell
      run: nix run nixpkgs.nix-build-uncached -c nix-build-uncached -I nixpkgs="$(jq -r '.["nixpkgs-unstable"].url' ./nix/sources.json)" shell.nix

  telegram:
    name: Telegram
    needs: [system, home-manager, shell]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v2.0.1

      - uses: yanzay/notify-telegram@v0.1.0
        with:
          chat: ${{ secrets.NOTIFICATION_CHAT_ID }}
          token: ${{ secrets.NOTIFICATION_TOKEN }}
          status: ${{ env.WORKFLOW_CONCLUSION }}
        if: env.WORKFLOW_CONCLUSION != 'success'
