name: "Update and build"
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        cachixName:
          - reedrw
        machines:
          - nixos-desktop
          - nixos-t400
          - nixos-t520

    runs-on: ubuntu-latest
    steps:
    - name: Install nix
      uses: cachix/install-nix-action@v11
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Checkout repository
      uses: actions/checkout@v2.3.3

    - name: Free disk space
      run: |
        df -h
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h

    - name: Setup cachix
      uses: cachix/cachix-action@v7
      with:
        name: ${{ matrix.cachixName }}
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Update sources
      run: ./update-all.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build nix-shell
      run: nix-build -I nixpkgs="$(jq -r '.["nixpkgs-unstable"].url' ./nix/sources.json)" shell.nix

    - name: Build system
      run: ./ci.sh system
      env:
        machine: ${{ matrix.machines }}

    - name: Build home-manager
      run: ./ci.sh home-manager

    - name: Update nix-index database
      run: nix-shell -p nix-index --run "nix-index -d ./modules/comma"

    - name: Commit and push
      uses: EndBug/add-and-commit@v5
      with:
        author_name: GitHub Action
        author_email: action@github.com
        message: "automated update"
        add: "--all"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
