name: "Update and build"
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Update sources
    strategy:
      matrix:
        cachixName:
          - reedrw
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: technote-space/auto-cancel-redundant-workflow@v1.6.3

    - name: Install nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Checkout repository
      uses: actions/checkout@v2.3.4

    - name: Update sources
      run: ./update-all.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create diff
      run: |
        mkdir -p ~/artifact
        git diff --oneline --graph > ~/artifact/update.diff

    - name: Upload diff artifact
      uses: actions/upload-artifact@v2
      with:
        name: update.diff
        path: ~/artifact/update.diff

  nix-index:
    name: Update nix-index database
    needs: update
    runs-on: ubuntu-latest
    steps:
    - name: Install nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Checkout repository
      uses: actions/checkout@v2.3.4

    - name: Download diff artifact
      uses: actions/download-artifact@v2
      with:
        name: update.diff
        path: ~/artifact/update.diff

    - name: Apply diff
      run: |
        git apply ~/artifact/update.diff/update.diff

    - name: Update nix-index database
      run: |
        mkdir -p ~/artifact/nix-index
        nix-shell -p nix-index --run "nix-index -f $(jq -r '.["nixpkgs-unstable"].url' ./nix/sources.json) -d ~/artifact/nix-index"

    - name: Upload nix-index artifact
      uses: actions/upload-artifact@v2
      with:
        name: nix-index db
        path: ~/artifact/nix-index/files

  shell:
    name: Build nix-shell
    needs: update
    strategy:
      matrix:
        cachixName:
          - reedrw
    runs-on: ubuntu-latest
    steps:
    - name: Install nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Setup cachix
      uses: cachix/cachix-action@v7
      with:
        name: ${{ matrix.cachixName }}
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Checkout repository
      uses: actions/checkout@v2.3.4

    - name: Download diff artifact
      uses: actions/download-artifact@v2
      with:
        name: update.diff
        path: ~/artifact/update.diff

    - name: Apply diff
      run: |
        git apply ~/artifact/update.diff/update.diff

    - name: Build nix-shell
      run: nix-build -I nixpkgs="$(jq -r '.["nixpkgs-unstable"].url' ./nix/sources.json)" shell.nix

  system:
    name: Build system
    needs: update
    strategy:
      matrix:
        cachixName:
          - reedrw
        machines:
          - nixos-desktop
          - nixos-t400
          - nixos-t520

    runs-on: ubuntu-latest
    steps:
    - name: Install nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Setup cachix
      uses: cachix/cachix-action@v7
      with:
        name: ${{ matrix.cachixName }}
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Checkout repository
      uses: actions/checkout@v2.3.4

    - name: Download diff artifact
      uses: actions/download-artifact@v2
      with:
        name: update.diff
        path: ~/artifact/update.diff

    - name: Apply diff
      run: |
        git apply ~/artifact/update.diff/update.diff

    - name: Build system
      run: ./ci.sh system
      env:
        machine: ${{ matrix.machines }}

  home-manager:
    name: Build home-manager
    needs: update
    strategy:
      matrix:
        cachixName:
          - reedrw
    runs-on: ubuntu-latest
    steps:
    - name: Install nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Setup cachix
      uses: cachix/cachix-action@v7
      with:
        name: ${{ matrix.cachixName }}
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Checkout repository
      uses: actions/checkout@v2.3.4

    - name: Download diff artifact
      uses: actions/download-artifact@v2
      with:
        name: update.diff
        path: ~/artifact/update.diff

    - name: Apply diff
      run: |
        git apply ~/artifact/update.diff/update.diff

    - name: Build home-manager
      run: ./ci.sh home-manager

  push:
    name: Commit and push
    needs: [update, nix-index, shell, system, home-manager]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4

    - name: Download diff artifact
      uses: actions/download-artifact@v2
      with:
        name: update.diff
        path: ~/artifact/update.diff

    - name: Apply diff
      run: |
        git apply ~/artifact/update.diff/update.diff

    - name: Download nix-index artifact
      uses: actions/download-artifact@v2
      with:
        name: nix-index db
        path: ~/artifact/nix-index/files

    - name: Replace nix-index db
      run: |
        rm -v ./modules/comma/files
        cp -v ~/artifact/nix-index/files/files ./modules/comma

    - name: Commit and push
      uses: EndBug/add-and-commit@v5
      with:
        author_name: GitHub Action
        author_email: action@github.com
        message: "automated update"
        add: "--all"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
