name: "Update nix-index cache"
on:
  schedule:
    - cron: '0 0 1 * 0'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: tibdex/github-app-token@v1.1.1
      id: generate-token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Install Doppler CLI
      uses: dopplerhq/cli-action@v1

    - name: Install nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Checkout repository
      uses: actions/checkout@v2.3.4

    - run: nix run nixpkgs.nix-index -c nix-index -d modules/comma -f https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ steps.generate-token.outputs.token }}
        author: reedbot[bot] <74506764+reedbot[bot]@users.noreply.github.com>
        commit-message: Update nix-index cache
        title: Update nix-index cache
        body: |
          - Update nix-index cache

          Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        branch: update-nix-index
