name: "Update dependencies"
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  update:
    strategy:
      matrix:
        cachixName:
          - reedrw
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: technote-space/auto-cancel-redundant-workflow@v1.6.3

    - name: Install nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Checkout repository
      uses: actions/checkout@v2.3.4

    - uses: tibdex/github-app-token@v1.1.1
      id: generate-token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Download niv
      run: nix-shell -p niv --run exit

    - name: Update sources
      run: ./update-all.sh

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ steps.generate-token.outputs.token }}
        author: reedbot[bot] <74506764+reedbot[bot]@users.noreply.github.com>
        commit-message: Update dependencies
        title: Update dependencies
        body: |
          - Dependency updates

          Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        branch: update-dependencies

    - name: Send notification
      uses: yanzay/notify-telegram@v0.1.0
      if: job.status != 'success'
      with:
        chat: ${{ secrets.NOTIFICATION_CHAT_ID }}
        token: ${{ secrets.NOTIFICATION_TOKEN }}
        status: ${{ job.status }}
